// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oxepmjegeytkoxniegnv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im94ZXBtamVnZXl0a294bmllZ252Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4OTg0MzgsImV4cCI6MjA2MDQ3NDQzOH0.AbpL5KPPgOovtwWdgcl6br8tTrLiFXHrkgkG3fHQ1Sc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);